name: school_project
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  audioplayers: ^1.0.1
  carousel_slider: ^4.1.1
  cloud_firestore: ^3.4.4
  cupertino_icons: ^1.0.2
  dio: ^5.0.0
  # dropdown_search: ^5.0.2
  dropdownfield: ^1.0.3
  file_picker: ^5.0.1
  firebase_auth: ^3.6.3
  firebase_core: ^1.20.1
  firebase_storage: ^10.3.6
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.5.4
  flutterfire_ui: ^0.4.3+5
  google_sign_in: ^5.4.1
  just_audio: ^0.9.28
  line_awesome_flutter: ^2.0.0
  mobx: ^2.0.7+5
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  smart_reply: ^0.1.0
  theme_provider: ^0.5.0
  url_launcher: ^6.1.5
  webview_flutter: ^3.0.4
  webview_flutter_web: ^0.1.0+4

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: SFProText
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Thin.otf
          weight: 100
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Text-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Text-Bold.otf
          weight: 700
