// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYf0LeiloNoTH3CXThX2NlNzatRETBLW8',
    appId: '1:139074668861:web:3e1fb17813e39926fc1d54',
    messagingSenderId: '139074668861',
    projectId: 'my-being-you',
    authDomain: 'my-being-you.firebaseapp.com',
    storageBucket: 'my-being-you.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZZ5hJhLZg0OyBQLbnuo34q-FlnLt6aYs',
    appId: '1:139074668861:android:64a51a0a8ac85382fc1d54',
    messagingSenderId: '139074668861',
    projectId: 'my-being-you',
    storageBucket: 'my-being-you.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3p8wc1xvIpIdfokgl5ZqkcYcq_h4zX7E',
    appId: '1:139074668861:ios:89a921b72d296d43fc1d54',
    messagingSenderId: '139074668861',
    projectId: 'my-being-you',
    storageBucket: 'my-being-you.appspot.com',
    iosClientId: '139074668861-j5ptq60q3aj7kspfl901jbi69kjv6rkb.apps.googleusercontent.com',
    iosBundleId: 'com.example.schoolProject',
  );
}
